"""Optional LLM rendering of plan artifact content.

Falls back to the deterministic templates in artifacts/templates.py
whenever the LLM is unavailable or returns something unusable. The
rendered content must still start with the revert comment header, so a
bad generation can never produce an unattributable file.
"""

from __future__ import annotations

from pathlib import Path

ARTIFACT_TEMPLATE = Path(__file__).resolve().parent.parent / "explain" / "prompts" / "artifact.md"
_HEADER_PREFIX = "# generated by kernel-surface-ledger"


def _prompt(step: dict, report: dict) -> str:
    """Render the artifact.md template for one plan step."""
    template = ARTIFACT_TEMPLATE.read_text()
    workload = next(
        (
            w
            for w in sorted(report["workloads"], key=lambda x: x["id"])
            if set(step["targets"]) & set(w["touches"])
        ),
        None,
    )
    observed = ",".join(sorted(workload["touches"])) if workload else "(none observed)"
    for key, value in {
        "action": step["action"],
        "targets": ", ".join(step["targets"]),
        "kernel_release": report["meta"]["kernel_release"],
        "arch": report["meta"]["arch"],
        "distro": report["meta"]["distro"],
        "comm": workload["comm"] if workload else "(host-wide change)",
        "observed_syscalls": observed,
    }.items():
        template = template.replace("{{" + key + "}}", value)
    return template


def maybe_render_artifact(step: dict, report: dict, fetch) -> None:
    """Replace plan[].artifact.content in place if the LLM produces usable output.

    ``fetch`` is explain.explain._cached_or_fetch; injected so tests can
    stub the network. Any failure leaves the deterministic template in
    place untouched.
    """
    answer = fetch(_prompt(step, report))
    if not isinstance(answer, str):
        return
    content = answer.strip()
    # Strip markdown fences the model may add despite instructions.
    if content.startswith("```"):
        first_newline = content.find("\n")
        content = content[first_newline + 1 :] if first_newline != -1 else ""
        if content.endswith("```"):
            content = content[: -len("```")]
        content = content.strip()
    if not content.startswith(_HEADER_PREFIX):
        return  # unattributable output: keep deterministic template
    step["artifact"]["content"] = content + "\n"
