"""Template renderers for each plan action's artifact file."""

from __future__ import annotations

GENERATED_BY = "# generated by kernel-surface-ledger - review before applying"


def modprobe_blacklist(targets: list[str]) -> str:
    """Render a modprobe.d blacklist with install overrides."""
    lines = [
        f"{GENERATED_BY} - revert: rm /etc/modprobe.d/ksl-blacklist.conf && update-initramfs -u",
        "# blacklist alone does not prevent explicit insertion or autoload, so each",
        "# module also gets an install override pointing at /bin/false.",
        "",
    ]
    for target in sorted(targets):
        lines.append(f"blacklist {target}")
        lines.append(f"install {target} /bin/false")
    return "\n".join(lines) + "\n"


def sysctl_fragment(settings: dict[str, str]) -> str:
    """Render a sysctl.d fragment from ordered key/value settings."""
    lines = [
        f"{GENERATED_BY} - revert: rm /etc/sysctl.d/99-ksl-hardening.conf && sysctl --system",
        "",
    ]
    for key in sorted(settings):
        lines.append(f"{key} = {settings[key]}")
    return "\n".join(lines) + "\n"


SYSCTL_TARGET_VALUES: dict[str, dict[str, str]] = {
    "vm.unprivileged_userfaultfd": {"vm.unprivileged_userfaultfd": "0"},
    "kernel.perf_event_paranoid": {"kernel.perf_event_paranoid": "3"},
    "kernel.kptr_restrict": {"kernel.kptr_restrict": "2"},
    "kernel.dmesg_restrict": {"kernel.dmesg_restrict": "1"},
}


def seccomp_json(unit: str, denied: list[str]) -> str:
    """Render an OCI seccomp profile denying the given syscall names."""
    import json

    profile = {
        "defaultAction": "SCMP_ACT_ALLOW",
        "syscalls": [
            {"names": sorted(denied), "action": "SCMP_ACT_ERRNO", "errnoRet": 38}
        ],
    }
    body = json.dumps(profile, indent=2, sort_keys=True)
    return f"# {unit}: deny listed syscalls via OCI seccomp\n{body}\n"


def systemd_confine(unit: str) -> str:
    """Render a systemd drop-in restricting namespaces and privilege."""
    return "\n".join(
        [
            f"{GENERATED_BY} - revert: rm /etc/systemd/system/{unit}.d/ksl-confine.conf && systemctl daemon-reload",
            "[Service]",
            "NoNewPrivileges=yes",
            "RestrictNamespaces=yes",
            "",
        ]
    )


def udev_rule(node: str, group: str = "kvm") -> str:
    """Render a udev rule restricting a device node to its owning group."""
    name = node.rsplit("/", 1)[-1]
    return (
        f"{GENERATED_BY} - revert: rm the rule then: udevadm control --reload && udevadm trigger {node}\n"
        f'KERNEL=="{name}", GROUP="{group}", MODE="0660"\n'
    )


def render(action: str, targets: list[str]) -> str:
    """Dispatch to the right renderer; unknown actions get a stub header."""
    if action == "blacklist_module":
        return modprobe_blacklist(targets)
    if action == "sysctl_set":
        merged: dict[str, str] = {}
        for target in targets:
            merged.update(SYSCTL_TARGET_VALUES.get(target, {}))
        return sysctl_fragment(merged)
    if action == "systemd_confine":
        unit = targets[0] if targets else "unknown.service"
        return systemd_confine(unit)
    if action == "remove_devnode_access":
        return udev_rule(targets[0] if targets else "/dev/kvm")
    if action == "seccomp_filter":
        denied = [t for t in targets if not t.startswith("/")]
        return seccomp_json("service", denied or ["io_uring_setup"])
    return f"{GENERATED_BY}\n# no deterministic template for action={action}\n"
